services:
  windows:
    image: dockurr/windows
    container_name: windows
    environment:
      VERSION: "2025"
      RAM_SIZE: "64G"
      CPU_CORES: "8"
      DISK_SIZE: "250G"
      DISK2_SIZE: "80G"
      DISK3_SIZE: "64G"
      USERNAME: "MasR"
      PASSWORD: "R12345"
    devices:
      - /dev/kvm
      - /dev/net/tun
    cap_add:
      - NET_ADMIN
    ports:
      - 8006:8006
      - 3389:3389
      - 3389:3389/tcp
      - 3389:3389/udp
    volumes:
      - ./windows:/storage
      - ./windows:/storage2
      - ./windows:/storage3
    restart: always
    stop_grace_period: 2m
